server:
  port: ${SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_NAME}
  config:
    import: optional:configserver:${CONFIG_SERVER_URL}

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:}
      timeout: ${REDIS_TIMEOUT:2000ms}
      jedis:
        pool:
          max-active: ${REDIS_POOL_MAX_ACTIVE:10}
          max-idle: ${REDIS_POOL_MAX_IDLE:10}
          min-idle: ${REDIS_POOL_MIN_IDLE:1}
          max-wait: ${REDIS_POOL_MAX_WAIT:2000ms}

  jackson:
    serialization:
      fail-on-empty-beans: false

  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVER}
    properties:
      sasl.mechanism: PLAIN
      security.protocol: SASL_SSL
      sasl.jaas.config: >
        org.apache.kafka.common.security.plain.PlainLoginModule required                                                                          
        username='${KAFKA_API_KEY}'                                                                                                               
        password='${KAFKA_API_SECRET}';
      session.timeout.ms: 45000

    consumer:
      group-id: roadmap-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      enable-auto-commit: false
      max-poll-records: 50
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: true

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5

    listener:
      ack-mode: manual_immediate

app:
  kafka:
    dlt-topic: ${KAFKA_USER_DLT_TOPIC}
    atom-dlt-topic: ${KAFKA_ATOM_DLT_TOPIC}
    capsule-dlt-topic: ${KAFKA_CAPSULE_DLT_TOPIC}
    growthTrack-dlt-topic: ${KAFKA_GROWTH_TRACK_DLT_TOPIC}
    talentRoute-dlt-topic: ${KAFKA_TALENT_ROUTE_DLT_TOPIC}
    mentor-dlt-topic: ${KAFKA_MENTOR_DLT_TOPIC}